spring:
  application:
    name: greeting-service
  datasource:
    username: freedb_user_S
    password: 5Ym9xhFwqK9&9es
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_greeting
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
greeting:
  message: Hello from spring boot

logging:
  pattern:
    level: "%5p [${spring.application.name:}"
