spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/greeting
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
