spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/greeting

  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true
