apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service
  labels:
    app: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
        - name: greeting-service
          image: "ghcr.io/mdsagir/greeting-service:latest"
          volumeMounts:
            - mountPath: /workspace/config
              name: greeting-config
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8080
 #         env:
  #          - name: GREETING_MESSAGE
  #            value: Hello from Kubernetes!
      volumes:
        - name: greeting-config
          configMap:
            name: greeting-config
