version: "3.8"
services:

  catalog-service:
    depends_on:
      - greeting-mysql
    image: "greeting-service"
    container_name: "greeting-service"
    ports:
      - "8080:8080"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/greeting


  greeting-mysql:
    image: "mysql:latest"
    container_name: "greeting-mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=greeting
