version: "3.8"
services:

  catalog-service:
    image: "ghcr.io/mdsagir/greeting-service:latest"
    container_name: "greeting-service"
    ports:
      - "8080:8080"
    environment:
      - GREETING_MESSAGE=Hello from Docker!
